// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseAssistant.Api.Data;

#nullable disable

namespace WarehouseAssistant.Api.Data.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260620090353_UseIntegerQuantities")]
    partial class UseIntegerQuantities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromWarehouseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ToWarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.MovementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("MovementId", "NomenclatureId")
                        .IsUnique();

                    b.ToTable("MovementItems");
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.Nomenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Nomenclatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ноутбук"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Монитор"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Клавиатура"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Мышь"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Сетевой кабель"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Принтер"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Тонер"
                        });
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Основной склад"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Розничный склад"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Склад брака"
                        });
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.Movement", b =>
                {
                    b.HasOne("WarehouseAssistant.Api.Domain.Warehouse", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarehouseAssistant.Api.Domain.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.MovementItem", b =>
                {
                    b.HasOne("WarehouseAssistant.Api.Domain.Movement", "Movement")
                        .WithMany("Items")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseAssistant.Api.Domain.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("WarehouseAssistant.Api.Domain.Movement", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
